/**
 * Generated by tsnapi — public API snapshot of `viteplus-preset-bjmhe`
 */
// #region Interfaces
export interface LibOptions {
  entry?: "index" | "shallow" | "all" | Exclude<TsdownInputOption, string>;
  inlineDeps?: (string | RegExp)[];
}
// #endregion

// #region Functions
export declare function lib({
  entry,
  inlineDeps
}?: LibOptions, _?: UserConfig): UserConfig;
export declare function nodeLib(_?: LibOptions, _?: UserConfig): UserConfig;
// #endregion